# Generated by Django 4.2.11 on 2024-04-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar_id',
            field=models.CharField(default=123456789, max_length=50),
            preserve_default=False,
        ),
    ]
