# Generated by Django 4.2.11 on 2024-04-23 14:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_aadhar_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('unique_user_id', models.UUIDField()),
                ('loanId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_type', models.CharField(max_length=100)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_period', models.PositiveIntegerField()),
                ('disbursement_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='aadhar_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
